lib/api/api.js
Dealing with #15.  I'm hitting this in production.
=> Add missing error callback

lib/utils/utils.js
User valid uri has the following forms:
- udp://my.full.domain.com
- udp://my.full.domain.com:12345
- udp://123.234.222.101
- udp://123.234.222.101:12345
- udp://[ad90::2232:0001:1111]
- udp://[ad90::2232:0001:1111]:12345
Namely, dns domains, ipv4 addresses, and ipv6 addresses [in brackets], with an optional port number.
=> Added function to check if uri is valid

lib/api/api.js, lib/crypto/hmac.js, test/api/api.prepareTransfers.js
Adds an hmac to the signature of the outputs of a bundle given an hmac key
=> Added hmac feature

lib/api/api.js, lib/utils/inputValidator.js, lib/utils/utils.js
related to https://github.com/iotaledger/iri/pull/303
=> Feature: use nonce to add attachment timestamp - parsing

lib/api/api.js
Better yet, could be changed to
`if ( !( ... && ... ) )`
=> Input validation logic typos (?)

README.md
- added missing transaction hash parameter for promoteTransaction()
- added details for transfers array
=> Fixed parameters for promote in documentation

lib/iota.js
This suggestion is intended for syntactic consistency in the recently refactored code; it does not introduce any change in functionality.
=> Improve consistency within settings assignments

lib/utils/inputValidator.js, test/valid/valid.isObject.js
`isObject` would return true in case the value passed in accidentally is `null` or an `array`. 
It might make sense to just check for `null` values but there's a separate util for `arrays`.
=> isObject validation

lib/utils/makeRequest.js
Includes a hotfix by @cvarley100 to get around breaking changes made in Facebook's metro bundler for React Native
https://github.com/facebook/metro/issues/65
=> Hotfix for React Native

lib/api/api.js, lib/crypto/hmac/hmac.js
Fix for https://github.com/iotaledger/iota.lib.js/issues/182
=> Fix offset and length parameters in curl calls

README.md
Change the link from Slack to Discord.
=> Change from Slack to Discord.

lib/api/api.js, lib/utils/makeRequest.js
Useful because if the node never responds, the old code just hangs. Forever.
=> Implement api timeout

lib/utils/makeRequest.js, test/utils/utils.batchedSend.js
Fixes #218  & #219
Added tests for `batchedSends` with both single and multiple input keys.
=> Fixes for batched send

README.md
Fixes #209 related to issues in multisig section & broken links.
=> Update multisig section in readme

packages/core/src/createGetInputs.ts, packages/core/test/integration/getInputs.test.ts, packages/core/test/integration/getNewAddress.test.ts
Fixes two cases of missing tests in getInputs
https://github.com/iotaledger/iota.lib.js/compare/next...chrisdukakis:test/getInputs?expand=1#diff-1855f0d8c3666a9cac916fb70a3d027cR129
=> Fix non-working tests in getInputs

README.md, api_reference.md, packages/core/README.md, packages/core/README_tpl.hbs, packages/core/src/createPrepareTransfers.ts, packages/core/src/createSendTrytes.ts, packages/core/src/generateAddress.ts, packages/extract-json/README.md, packages/extract-json/src/index.ts, packages/http-client/README.md, packages/validators/README.md, packages/validators/src/validators.ts
Updates and fixes on documentation.
=> Documentation updates & fixes

README.md, api_reference.md, packages/core/README.md, packages/core/src/composeAPI.ts, packages/core/src/createAttachToTangle.ts, packages/core/src/createStoreTransactions.ts
Update readme and PoWbox links
=> update readme and PoWbox links

packages/converter/src/ascii.ts
Removes redundant char code check from `asciiToTrytes()`.
Fixes #243
=> asciiToTrytes: Remove redundant char code check

.github/issue_template.md
Fixes minor issues with the issue template
Not applicable
=> Fix minor issues with issue template

package-lock.json, package.json
Update `lint-staged` to version 8.0.3
Fixes #295
=> chore(package): update lint-staged to version 8.0.3

package-lock.json, package.json, packages/core/package-lock.json, packages/core/package.json, packages/http-client/package-lock.json, packages/http-client/package.json, scripts/test-staged.js
- Update `lint-staged` to `8.0.4`
- Do not lint lockfiles
- Update `@types/bluebird` to `3.5.24`
Fixes #299
=> chore(package): update lint-staged to 8.0.4 & @types/bluebird to 3.5.24

examples/README.md
=> docs: update /examples readme file

.travis.yml, package-lock.json, package.json
Run commitlint in travis CI. It fails the build if one or more commit messages do not adhere to [conventional commit format](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).
Related to #292
=> chore: run commitlint in CI

packages/core/package-lock.json, packages/core/package.json, packages/http-client/package-lock.json, packages/http-client/package.json
Updates `nock` to `10.0.4`
Fixes #315
=> chore(package): update nock to 10.0.4

README.md
Update README to be consistent with other client libraries.
=> docs: update README.md to be consistent with other client libraries

package-lock.json, package.json, packages/core/package-lock.json, packages/core/package.json, packages/http-client/package-lock.json, packages/http-client/package.json, packages/multisig/package-lock.json, packages/multisig/package.json
Updates `@types/bluebird` to `3.5.25`
Fixes #321
=>  chore(package): update @types/bluebird to version 3.5.25

README.md, packages/core/test/integration/prepareTransfers.test.ts, packages/guards.ts, packages/types.ts, packages/validators/test/isInput.test.ts
Security level should not be an optional property of input objects. 
Fixes #325 
=> fix: input objects should have security level

api_reference.md
=> fix typo in api_reference

packages/http-client/src/httpClient.ts, packages/http-client/src/request.ts, packages/http-client/src/settings.ts, packages/http-client/test/batchedSend.test.ts, packages/http-client/test/batchedSend.ts, packages/http-client/test/isBatchableCommand.test.ts, packages/http-client/test/send.test.ts, packages/http-client/test/send.ts, packages/http-client/test/setSettings.test.ts
Fixes a few issues with batched requests: 
- adds support for batched `getTrytes`
- fixes milestone info in batched `getBalances`
- includes unbatched fields in all requests
- tests
- allow any batch size
=> fix: issues with batched requests

packages/signing/android/src/main/java/org/iota/ReactNativeSigning/SigningModule.java, packages/signing/android/src/main/java/org/iota/mobile/ByteArrayConverter.java, packages/signing/android/src/main/java/org/iota/mobile/Interface.java
Fixes `mobile` package renaming, introduced in: https://github.com/iotaledger/iota.js/commit/a09e7908381b1ed8dab7d0b7f7c1327f23455f89 
=> fix(signing): correct package name

packages/account/src/account.ts, packages/account/src/preset.ts, packages/account/test/account.test.ts, packages/persistence-adapter-level/src/persistenceAdapterLevel.ts, packages/persistence-adapter-level/test/persistenceAdapterLevel.test.ts, packages/persistence/src/persistence.ts, packages/persistence/test/persistence.test.ts, packages/types.ts
- Fix bug in transaction issuance, which would allow used inputs to persist in state.
- Pass correct context to preset functions (events were not emitted)
- Refactor transaction attachment routine.
=> fix(account): transaction issuance batch, attachment events

packages/account/src/preset.ts
Fixes a bug that led to invalidation of unfunded remainder address.
=> fix(account): remainder addresses persist in state

packages/account/src/preset.ts
Fix issues with repetition of transaction issuance routine and invalidation of included bundles.
=> fix(account): polling in transaction attachment

packages/account/src/account.ts
Adds support for tryte-string seed besides Int8Array
=> feat(account): accept string as seed

packages/http-client/src/httpClient.ts, packages/http-client/src/request.ts, packages/http-client/src/settings.ts, packages/http-client/test/send.test.ts, packages/http-client/test/send.ts
Adds [basic auth](https://github.com/iotaledger/iri/blob/6a0606e472f8385e5fef819ce0c800b1559d1c62/src/test/java/com/iota/iri/service/restserver/RestEasyTest.java#L130). Only works with **https**.
=> feat(http-client): basic auth

packages/core/src/createCheckConsistency.ts
Fixes a type error in `checkConsistency`
=> fix(core): type error in checkConsistency

packages/core/package-lock.json, packages/core/package.json, packages/multisig/package-lock.json, packages/multisig/package.json
Fixes #365 
- The `dependency` [bluebird](https://github.com/petkaantonov/bluebird) was updated from `3.5.4` to `3.5.5`.
<details>
<summary>Release Notes for v3.5.5</summary>
<p>Features:</p>
<ul>
<li>Added Symbol.toStringTag support to Promise (<a href="https://urls.greenkeeper.io/petkaantonov/bluebird/issues/1421" data-hovercard-type="pull_request" data-hovercard-url="/petkaantonov/bluebird/pull/1421/hovercard">#1421</a>)</li>
</ul>
<p>Bugfixes:</p>
<ul>
<li>Fix error in IE9 (<a href="https://urls.greenkeeper.io/petkaantonov/bluebird/issues/1591" data-hovercard-type="issue" data-hovercard-url="/petkaantonov/bluebird/issues/1591/hovercard">#1591</a>, <a href="https://urls.greenkeeper.io/petkaantonov/bluebird/issues/1592" data-hovercard-type="pull_request" …
=> chore(package): update bluebird to version 3.5.5

packages/unit-converter/package.json
=> fix(unit-converter): correct typings dir

package-lock.json, package.json, packages/account/package-lock.json, packages/account/package.json, packages/async-buffer/package-lock.json, packages/bundle/package-lock.json, packages/bundle/package.json, packages/cda/package-lock.json, packages/cda/package.json, packages/converter/package-lock.json, packages/converter/package.json, packages/core/package-lock.json, packages/curl/package-lock.json, packages/curl/package.json, packages/http-client/package-lock.json, packages/kerl/package-lock.json, packages/kerl/package.json, packages/multisig/package-lock.json, packages/pad/package-lock.json, packages/pad/package.json, packages/pearl-diver-react-native/package-lock.json, packages/persistence-adapter-level/package-lock.json, packages/persistence/package-lock.json, packages/signing/package-lock.json, packages/signing/package.json, packages/transaction-converter/package-lock.json, packages/transaction-converter/package.json, packages/transaction/package-lock.json, packages/transaction/package.json, packages/unit-converter/package-lock.json
Adds missing `core-js` dependencies.
Fixes #396
=> fix: add missing core-js dependencies

packages/account/src/account.ts
fix `pendingDeposit` & `pendingWithdrawal` events to emit once
=> fix(account): pending events emit once

packages/account/src/account.ts, packages/account/test/account.test.ts
Adds a noop handler on `error` events, to avoid crash.
Fixes #404 
=> fix(account): handle ungaught error events

package.json
=> fix: lint-staged config

packages/http-client/package-lock.json, packages/http-client/package.json, packages/http-client/src/request.ts
Use `url-parse` instead of node `url`, to be compatible with RN on android.
=> refactor(http-client): replace url with url-parse

packages/http-client/src/settings.ts
Replaces url import with `url-parse` in `settings.ts` too
=> fix(http-client): replace url import in settings

packages/account/package-lock.json, packages/account/src/account.ts, packages/async-buffer/package-lock.json, packages/bundle/package-lock.json, packages/cda/package-lock.json, packages/converter/package-lock.json, packages/core/package-lock.json, packages/http-client/package-lock.json, packages/kerl/package-lock.json, packages/multisig/package-lock.json, packages/pearl-diver-react-native/package-lock.json, packages/persistence-adapter-level/package-lock.json, packages/persistence/package-lock.json, packages/transaction/package-lock.json, packages/unit-converter/package-lock.json
The first address generated after a clean database and a new seed is somehow not registered into the module. For the first address no events are triggered if i deposit iota on that address. This is also not a start up problem because if i have already an address on startup registered all the events are triggered even though it is the first after startup. 
An example to better describe my problem:
```
Please send 2i to this address: WAFDRXFMMTIVXAYHNFLUNWRGQDREGVYA9ZBABZBMRYYDDYDAOVIKHVWQNORVUUFUFCHKEGCXTBREEPOU9BVZMWXZRD
{ available: 0, total: 0 } 
Please send 2i to this address: CJREEXYTDCLKRMGILVW9UVSM9IMLTYLOZYZOSVDMBTZINYYSYVFNBPWAFOTUTTNFPHUWYQVTXHXFGXSSBAYIPXGXQC
{ available: 2, total: 2 } 
Total Balance : 2 | Deposit (CJREEXYTDCLKRMGILVW9UVSM9IMLTYLOZYZOSVDMBTZINYYSYVFNBPWAFOTUTTNFP …
```
=> fix(account): first address not usable

package-lock.json, package.json, packages/core/package-lock.json, packages/pearl-diver-react-native/package-lock.json
=> chore: update dependencies

packages/account/src/account.ts
#Description
#404 should be finally fixed by this
Bug fix (non-breaking change which fixes an issue)
=> fix(account): first address not usable for deposit

README.md
Lerna has changed their domain name: https://github.com/lerna/lerna/issues/2033
N/A
=> docs: update lerna domain name

packages/bundle/README.md, packages/bundle/src/index.ts
Update documentation for bundle package.
- `addSignatureOrMessage` method added to `README.md`
- Add JSDoc comments to `valueSum` and add it to `README.md`
- `addTrytes`removed from docs as it was deprecated.
Fixes #429 
N/A
=> docs: update bundle documentation

packages/http-client/package-lock.json, packages/http-client/src/httpClient.ts, packages/http-client/src/request.ts, packages/http-client/src/settings.ts, packages/http-client/test/send.ts, packages/http-client/test/setSettings.test.ts
Please include a summary of the change. Include the motivation for the change.
Fixes # (issue)
=> chore: fix lint errors

package-lock.json, package.json, packages/account/package-lock.json, packages/async-buffer/package-lock.json, packages/bundle/package-lock.json, packages/cda/package-lock.json, packages/converter/package-lock.json, packages/core/package-lock.json, packages/kerl/package-lock.json, packages/multisig/package-lock.json, packages/pearl-diver-react-native/package-lock.json, packages/persistence-adapter-level/package-lock.json, packages/persistence/package-lock.json, packages/transaction/package-lock.json, packages/unit-converter/package-lock.json
Please include a summary of the change. Include the motivation for the change.
Fixes # (issue)
=> chore: update deps

package.json
Adds a lerna publish as npm script in the project root. No longer requires global installation.
=> feat: add lerna publish as npm script

README.md
Please include a summary of the change. Include the motivation for the change.
Fixes # (issue)
=> Add zero-value transaction example

packages/extract-json/package.json
fixes path of typings for extract-json module
Fixes https://github.com/iotaledger/iota.js/issues/455
I replicated the change locally on my machine to validate that the typings can be found by the compiler
=> fix(extract-json): fix typings path

lib/crypto/converter/words.js, lib/errors/inputErrors.js
When you have .every(), the body has to have "return" or it won't work.  
There wasn't an error in the errors/inputErrors for invalidBundleHash.  
Thanks for all your hard work!
=> Two small bugs (incorrect use of .every() and a missing error message)

packages/account/README.md
This PR adds basic docs for account module
- Documentation
N/A
- [] My code follows the contribution guidelines for this project
- [] I have performed a self-review of my own code
- [] New and existing unit tests pass locally with my changes
=> docs: add README.md for account module

.travis.yml
- Fixes CI config warnings and updates environment
- Allows Android CI to fail
- Fixes CI
N/A
=> fix(ci): Resolve Travis CI config warnings and update env

api_reference.md, packages/bundle-validator/README.md, packages/bundle/README.md, packages/checksum/README.md, packages/checksum/README_tpl.hbs, packages/converter/README.md, packages/core/README.md, packages/extract-json/README.md, packages/http-client/README.md, packages/signing/README.md, packages/transaction-converter/README.md, packages/transaction/README.md, packages/unit-converter/README.md, packages/validators/README.md
[This](https://github.com/iotaledger/iota.js/pull/462/files) PR updated the code comments/documentation for all packages but did not update the corresponding README files.
This PR updates all README files of the packages. Done by running `npm run docs`
- Documentation Fix
=> docs: update READMEs of packages

packages/kerl/package-lock.json
This PR updates [kerl](https://github.com/iotaledger/iota.js/tree/next/packages/kerl) package-lock.json file.
- [] My code follows the contribution guidelines for this project
- [] I have performed a self-review of my own code
- [] I have added tests that prove my fix is effective or that my …
=> chore: update package-lock.json

packages/http-client/src/request.ts, packages/http-client/test/send.test.ts
Fixes https://github.com/iotaledger/iota.js/issues/497
=> fix: use consistent error type for http exceptions

packages/pearl-diver-react-native/scripts/build-android.sh, packages/pearl-diver-react-native/scripts/build-ios.sh
This PR updates "branch" from develop to master. Also, updated --copt flag.
- Enhancement (a non-breaking change which adds functionality)
Tested by running `npm run build-ios` in [packages/pearl-diver-react-native](https://github.com/iotaledger/iota.js/tree/next/packages/pearl-diver-react-native) package. 
=> chore: update build scripts for pearl-diver-react-native

README.md, api_reference.md
Fixes https://github.com/iotaledger/iota.js/issues/504
- Documentation Fix
N/A
=> docs: update API reference

packages/http-client/package-lock.json, packages/http-client/package.json
Bump cross-fetch version to avoid a vulnerability on node-fetch
Trivial change on package.json. The version of the dependency library does exist at https://www.npmjs.com/package/cross-fetch/v/3.0.6
=> Fix. Bump cross-fetch version to avoid a vulnerability on node-fetch

packages/bundle-validator/package-lock.json, packages/bundle-validator/package.json, packages/checksum/package-lock.json, packages/checksum/package.json, packages/checksum/test/checksum.test.ts, packages/core/package-lock.json, packages/core/package.json, packages/extract-json/package-lock.json, packages/extract-json/package.json, packages/http-client/package-lock.json, packages/http-client/package.json, packages/kerl/package-lock.json, packages/kerl/package.json, packages/multisig/package-lock.json, packages/pad/package-lock.json, packages/pad/package.json, packages/transaction-converter/package-lock.json, packages/transaction-converter/package.json, packages/unit-converter/package-lock.json, packages/unit-converter/package.json, packages/validators/package-lock.json, packages/validators/package.json, packages/validators/test/validate.test.ts
This PR updates [ava](https://github.com/avajs/ava) to latest version. Updating this package should also fix some of the reported vulnerabilities. 
- Enhancement (a non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to not work as expected)
- Documentation Fix
- [] I have made …
=> chore: update ava across all packages

package-lock.json
This PR regenerates the package lock file at root level. This should fix some of the reported vulnerabilities by snyk due to out of sync lock file.
=> chore: regenerate package lock file

packages/bundle-validator/package-lock.json, packages/checksum/package-lock.json, packages/core/package-lock.json, packages/extract-json/package-lock.json, packages/kerl/package-lock.json, packages/pearl-diver-react-native/package-lock.json, packages/transaction-converter/package-lock.json, packages/validators/package-lock.json
This PR regenerates lock files for packages using `lerna clean && npm i && lerna bootstrap`.
=> chore: regenerate lock files for sub packages

package-lock.json
This PR updates `lodash` and `y18n` packages at the root level.
=> chore: update lodash & y18n packages

examples/address/src/index.ts
Fixed the terminology in the iota.js#chrysalis address example
- Documentation Fix
=> Fixed chrysalis example terminology

src/highLevel/sendAdvanced.ts
Fixed typo.
```
Lexigraphically -> Lexicographically
```
- [] I have performed a self-review of my own code
- [] New and existing unit tests pass locally with my changes
=> chore: Fix typo in sendAdvanced.ts
