iotaledger/iota.js

lib/api/api.js

TL;DR - The `addRemainder` function is miscalculating the final remainder because the `totalTransferValue` variable is set inside the loop, when it should be outside the loop.
----------
I believe I've located a bug in the transaction calculation code.  It seems that this kicks in when you are sending iotas that require you to bundle up iotas from a variety of addresses, so this only applies occasionally.
While working on the cli-app I noticed that none of my transfers were ever getting confirmed.  After a while I noticed that there were many transactions, not just my own, that were not getting confirmed and after some digging it appears to me that they problem is that the transactions in the bundle are not calculating the remainder iotas correctly.
I may be misunderstanding how the …

Fix transaction remainder calculation

---

lib/utils/asciiToTrytes.js

Since we are decoding in pairs, the length should be even. If odd, trailing 9 should be trimmed to avoid calculating an erroneous pair or an error should be returned.
Example 1
`toTrytes('A') = 'KB'`, adding trailing ’9’s to make 3 trytes: `'KB9'`.
`fromTrytes('KB9') = 'A￥'` which has a string length of `2`.
Meaning ascii chars: `65` + `65509` which is not correct.
Expected value is `A`, string length of `1`.
Example 2
`toTrytes('A') = 'KB'`, adding trailing ’9’s to make 5 trytes: `'KB999'`.
`fromTrytes('KB999') = 'A￥'` which has a string length of `3`.
Meaning ascii chars: `65` + `0` + `65509` which is not correct.
Expected value is `A`, string length of `2`.
_Here we added 3 trailing `9`s to account for a null character that is not printable. Since a user might want to include it, it is …

Added validation on fromTrytes

---

lib/api/api.js

Currently `findTransactions` doesn't work with `tags` because the padding of the hashes is broken. This change fixes that by correctly assigning modified hashes to the `searchValues` query object.

Fix padding 'tags' hashes in findTransactions

---

lib/iota.js

I need to make sure I can change the token from node to node as I change them, but currently the only place where the token is set is when the IOTA object is created.  
I noticed that there was a lot of duplicated code in the IOTA setup and the `changeNode` function, but `changeNode` wasn't keeping up with the main IOTA function.  I've refactored the setup code into a new `setSettings` function that can be shared by the main iota setup, and the `changeNode` function.
This simplifies the code and allows you to change all necessary settings when changing nodes.

Consolidate settings code

---

lib/multisig/multisig.js

typeof returns a string, not types. simplify to a check for falsy
values, so people can also do things like: `balance: null`.
fixes #67

multisig: fix type error

---

lib/crypto/signing/signing.js
lib/utils/utils.js

return false in case no matching bundle is found for the current
address. before it was throwing as the passed value to
`validateSignatures` in `crypto/signing.js` was `undefined`

validation: handle invalid bundles

---

examples/multisig.js

`c alled` is fixed to `called`

Fix typo in examples/multisig.js

---

lib/api/api.js
lib/utils/makeRequest.js

Enables parsing of `checkConsistency()` response in `utils.prepareResult()` to prevent type errors.

prevent type error in isPromotable

---

.travis.yml
lib/api/api.js
lib/api/apiCommands.js
lib/errors/inputErrors.js
lib/utils/makeRequest.js
test/api/api.getNewAddress.js

- Added `wereAddressesSpentFrom()` command, which checks if addresses were used in current or previous epoch.
- Refactored `getNewAddress()` to utilize the new method.

add wereAddressesSpentFrom() to api

---

package.json

gulp-nsp is using the spread operator since about a month ago and thus killed support for Node < 5.
Which is causing all travis builds to fail on the second job due to the usage of Node v.4.1.2 for that.
https://github.com/nodesecurity/gulp-nsp/commit/92de6321816a4a50e45282b1ec03a64674634047#diff-168726dbe96b3ce427e7fedce31bb0bcR14
A better way to handle this would be either to drop gulp all together or stop trying to run tests / support for Node v4.1.2 (and move the minimum version to Node 5+)

Failing Travis CI builds: dependency gulp-nsp's update broke support for Node versions <5.0.0

---

lib/api/api.js

Please review.
Instead of starting at index 0 to get the address for the remainder value, we can use the already present inputs and their respective address key index `keyIndex` to determine the largest (if not THE largest) already generated address index.
This should help transfers without a specified remainder address and a lot of used addresses because we won't need to regenerate all addresses starting from index 0.
I'm not sure about this change, waiting for comments.

Added method to speed remainder transfer

---

lib/api/api.js

This change allows more flexibility when providing inputs yourself since `bundle.addEntry` needs address without checksum and you only get a cryptic `Error: Illegal length provided` from `Kerl.prototype.absorb`

remove checksum from inputs in addRemainer

---

README.md

Updates readme to refer to `storeAndBroadcast` instead of broadcastAndStore
Fixes #173

Update readme to refer to storeAndBroadcast instead of broadcastAndStore

---

lib/iota.js
lib/utils/makeRequest.js

Cannot seem to query a node using the `--remote-auth` flag in IRI. This PR allows an IOTA constructor to consume username and password variables, and uses them when making http requests.
Fixes #34

Support for remote authentication

---

packages/core/test/integration/getAccountData.test.ts
packages/core/test/integration/nocks/findTransactions.ts
packages/core/test/integration/nocks/getBalances.ts
packages/core/test/integration/nocks/wereAddressesSpentFrom.ts

Adds test for `getAccountData` when called with `options.start > 0`.
Ensures `start + index` works:
https://github.com/iotaledger/iota.lib.js/pull/232/files#diff-7fa618e02ddc1cb618bed5a4bc853f3cR161
Related to #183 & #184  (change of this PR applies to `next` branch)
Added test brakes when replacing `start + i` w/ `0 + i` in line bellow:
https://github.com/iotaledger/iota.lib.js/pull/232/files#diff-7fa618e02ddc1cb618bed5a4bc853f3cR161

test getAccountData when called with start index > 0

---

.gitignore
README.md
packages/core/src/composeAPI.ts
packages/core/src/index.ts
packages/core/test/integration/composeAPI.test.ts
packages/http-client/src/httpClient.ts
packages/types.ts

- Fixes `composeAPI` export in core
- `composeAPI` now accepts `settings` object or provider factory such as [`createHttpClient`](https://github.com/iotaledger/iota.lib.js/tree/next/packages/http-client#module_http-client..createHttpClient)
https://github.com/chrisdukakis/iota.lib.js/blob/2e5ca8d57922bb0ca45cc3dc97878213262b7a08/packages/core/test/integration/composeAPI.test.ts

fix export of composeAPI and have it accept provider factory

---

.gitignore
.travis.yml
lerna.json
package-lock.json
package.json
packages/bundle-validator/package.json
packages/bundle/package.json
packages/checksum/package.json
packages/converter/package.json
packages/core/package-lock.json
packages/core/package.json
packages/curl/package.json
packages/extract-json/package.json
packages/http-client/package-lock.json
packages/http-client/package.json
packages/kerl/package-lock.json
packages/kerl/package.json
packages/multisig/package-lock.json
packages/multisig/package.json
packages/pad/package.json
packages/samples/package.json
packages/signing/package.json
packages/transaction-converter/package.json
packages/unit-converter/package-lock.json
packages/unit-converter/package.json
packages/validators/package.json

- Bootstrap with `prepare` script instead of deprecated `prepublish`
- Update root scripts to use npm
- Do not ignore package-lock files
- Update `.travis.yml`

Use "prepare" to build packages & run scripts with npm

---

README.md

Just added a } to close options object on prepareTransfers example

missing } on options object on prepareTransfers()

---

package-lock.json
package.json

Bumps `jshint` to 2.9.6, fixing a minor vulnerability in an older version of `lodash` (see https://github.com/jshint/jshint/pull/3283)
`npm audit` now reports `no known vulnerabilities found`

Upgrade jshint to 2.9.6

---

api_reference.md
packages/core/README.md
packages/core/src/composeAPI.ts
packages/core/src/createCheckConsistency.ts
packages/core/src/createPromoteTransaction.ts
packages/core/src/errors.ts
packages/core/src/index.ts
packages/core/test/integration/checkConsistency.test.ts
packages/core/test/integration/nocks/checkConsistency.ts
packages/types.ts

- Fixes wrong `tails` field in `checkConsistency` command.
- Add `info` field in `CheckConsistencyResponse` type.
- Optionally uses `info` field as error message in case state is `false` and `rejectWithReason: true`.
- `promoteTransaction` calls `checkConsistency` with `rejectWithReason: true` by default, to propagate error message from `info` field.

checkConsistency: fix `tails` field & optionally reject with reason if state is false [next branch]

---

lib/api/api.js
lib/utils/makeRequest.js

- Add `info` field in `CheckConsistencyResponse` type.
- Optionally uses `info` field as error message in case state is `false` and `rejectWithReason: true` option is set to true.
- `promoteTransaction` calls `checkConsistency` with `rejectWithReason: true` by default, to propagate error message from `info` field.
Related PR for `next` branch & `@iota/core`: https://github.com/iotaledger/iota.lib.js/pull/251

checkConsistency: optionally reject with reason if state is false

---

packages/core/src/createPrepareTransfers.ts
packages/core/src/createPromoteTransaction.ts
packages/core/src/createSendTransfer.ts
packages/core/test/integration/prepareTransfers.test.ts
packages/multisig/src/multisig.ts
packages/types.ts
packages/validators/src/validators.ts
packages/validators/test/isTransfer.test.ts

Makes `message` & `tag` fields of [transfer object](https://github.com/iotaledger/iota.lib.js/compare/next...chrisdukakis:fix/transfer-object?expand=1#diff-94ae1bf38dc25cd5698868b4719fa369) optional.

Optional message & tag fields in transfer object

---

README.md
lib/api/api.js

If `getTransactionsToApprove()` is called with an old reference in relation to a given depth, the call will sometimes fail with [`"Reference transaction is too old"`](https://github.com/iotaledger/iri/blob/06ad631a438b07e932ea3de58ffac6e4c5b6e74b/src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java#L123) exception.
This PR addresses this issue by adding `adjustDepth` option to `getTransactionsToApprove`. This feature is now utilized by default in `promoteTransaction()`. If the option is set to true, `depth` is incremented upon failure, up to `maxDepth` (which is currently `15`).
Fixes #264

Retry with larger depth if reference transaction is too old

---

packages/core/src/createGetAccountData.ts
packages/core/test/integration/getAccountData.test.ts

Populates `accountData.transactions` list with hashes.
In the future a single `findTransactions()` call will be used to improve performance.
This would require to remove the deprecated `transfers` field.
Fixes #166

Populate accountData.transactions with hashes

---

api_reference.md
packages/extract-json/README.md
packages/extract-json/src/index.ts
packages/extract-json/test/extractJson.test.ts

Adds support for number extraction in [`@iota/extract-json`] according to: https://github.com/iotaledger/iota.lib.js/issues/231#issuecomment-402383449
Thanks @obany for this nice fix!
Fixes #231

Extract numbers from json-encoded fragments

---

packages/core/src/createGetBundlesFromAddresses.ts
packages/core/test/integration/nocks/findTransactions.ts

Fixes `bundles` query in `getBundlesFromAddresses`. This issue propagated in `getAccountData` & `getTransfers`, resulting to missing txs.

Fix bundle query in getBundlesFromAddresses

---

packages/core/src/createPrepareTransfers.ts
packages/core/test/integration/prepareTransfers.test.ts
packages/guards.ts
packages/types.ts
packages/validators/test/isInput.test.ts

- Adds validation for `input.balance`
- Makes `input.security` optional and sets default value to `2`
Fixes #277

Input objects: Add balance validation & set default security to 2

---

packages/core/src/createGetInputs.ts
packages/core/test/integration/getAccountData.test.ts
packages/core/test/integration/getInputs.test.ts
packages/core/test/integration/nocks/getBalances.ts

Fixes `getInputs` to filter out addresses without balance.

filter inputs with zero balance

---

packages/core/src/createPrepareTransfers.ts
packages/core/test/integration/prepareTransfers.test.ts

Fixes a minor issue in selection of initial index to get new remainder address. This improves speed of `prepareTransfers`.

fix remainder address start index

---

README.md
api_reference.md
packages/core/README.md
packages/core/src/createAttachToTangle.ts
packages/core/src/createBroadcastBundle.ts
packages/core/src/createBroadcastTransactions.ts
packages/core/src/createPrepareTransfers.ts
packages/core/src/createSendTrytes.ts
packages/core/src/createStoreAndBroadcast.ts
packages/core/src/createStoreTransactions.ts

Clarifies that is required to store transaction trytes before broadcasting to network.

Update docs to clarify necessity of storing trytes before broadcasting.

---

commitlint.config.js
lerna.json
package-lock.json
package.json

Enforces conventional commits with help of [`commitlint`](https://github.com/marionebl/commitlint). Then lerna will be able to bump version & populate conventional changelog according to introduced changes.
This is a first step for automating release lifecycle of iota.js (https://github.com/iotaledger/iota.js/issues/292).

chore: add commit message linter

---

packages/http-client/src/request.ts
packages/http-client/test/send.test.ts

This PR parses and returns JSON encoded errors of bad requests. A general `"Bad request"` error was displayed before this change, instead of specific error messages returned by IRI.
Perhaps we could return the JSON object as is, and not return the error field as string only... For now just returning `error` field seems fine I think...
Fixes #303

fix: parsing of json encoded request errors

---

packages/core/README.md
packages/core/package-lock.json
packages/core/src/composeAPI.ts
packages/core/test/integration/composeAPI.test.ts
packages/http-client/package-lock.json
packages/http-client/src/httpClient.ts
packages/kerl/package-lock.json
packages/multisig/package-lock.json
packages/pearl-diver-react-native/package-lock.json
packages/types.ts
packages/unit-converter/package-lock.json

- Fixes return type of `composeAPI`
- Removes `CreateProvider` type 
- `composeAPI` now accepts `Settings` object only
- Adds `network: Provider` field to `Settings` object
- Allow overriding `network` with `overrideNetwork(network: Provider)`

fix: API return type

---

lib/api/api.js
lib/api/apiCommands.js
test/api/api.getBalances.js
test/api/apiCommands.js

IRI [getBalances](https://iota.readme.io/reference#getbalances) endpoint accepts an optional "tips" parameter. The library does not provide support for users for passing in tips parameter. This commit updates getBalances endpoint to accept "tips" as an optional parameter.
Fixes https://github.com/iotaledger/iota.js/issues/313
- Added unit test coverage
- Manually tested with 
```
const IOTA = require('iota.lib.js');
const iota = new IOTA({ provider: 'https://nodes.thetangle.org:443' });
const seed = 'TEST9TEST9TEST';
const options = { start: 0 };
// Test getAccountData as it uses getBalances internally
iota.api.getAccountData(seed, options, console.info);
// Test getInputs as it uses getBalances internally
iota.api.getInputs(seed, options, console.info);
// Test prepareTransfers as it …
```

Add (optional) tips param to getBalances api

---

package.json

Disable prettier formatting of staged markdown files on precommit.

fix: disable prettier formatting of markdown files

---

lib/api/api.js

[isPromotable](https://github.com/iotaledger/iota.js/blob/d1d3aa57f7bb3879bc073cc4e59c9b5e4b83deda/lib/api/api.js#L1989) doesn't terminate the execution of function once the promise is rejected.
```
const IOTA = require('iota.lib.js');
const iota = new IOTA({ provider: 'http://localhost:14265' });
iota.api.setApiTimeout(5000);
iota.api.isPromotable('9'.repeat(81)).catch(console.error); // TypeError: Cannot read property 'state' of null
```
Related issue - https://github.com/iotaledger/trinity-wallet/issues/712
- Tested using the above script by forcing promise rejection.

Terminate execution of isPromotable api method once promise is rejected

---

lib/utils/utils.js
test/utils/utils.checksum.js

Updated [addChecksum](https://github.com/iotaledger/iota.js/blob/develop/lib/utils/utils.js#L62) to accept trit arrays and array of trit arrays (Similar to how it used to work for trytes).
- Added unit test coverage

Update #addChecksum util to accept trit arrays

---

.travis.yml

Prevents Android CI from failing on newer versions of `iotaledger/entangled` (such as the one included in #355), which require Android API level 27.

fix(ci): add API level 27 to Android CI

---

packages/checksum/README.md
packages/checksum/src/index.ts
packages/checksum/test/checksum.test.ts
packages/core/src/createFindTransactions.ts
packages/core/src/createGetBalances.ts
packages/core/src/createGetNewAddress.ts
packages/core/src/createIsReattachable.ts
packages/core/src/createWereAddressesSpentFrom.ts

My initial issue was with `removeChecksum`: it throws `INVALID_ADDRESS` when it receives an empty array as input.
After discussing with Chris I removed the array support (polymorphism) of `addChecksum` and `removeChecksum`.
That makes the code and the doc simpler while the array support is easily accessible with `addresses.map(removeChecksum)`
It depends if `add/removeChecksum` were used with arrays.

refactor(checksum): remove array support

---

lib/utils/utils.js
test/utils/utils.checksum.js

Retains the original behavior of `addChecksum`

Retain original behavior of addChecksum

---

lib/utils/utils.js

`value` in transaction uses 27 trytes but during trytes to transaction object only 11 trytes were being used.
This PR allocates correct (27 trytes) during trytes to transaction object conversion.
Related https://github.com/iotaledger/iota.js/pull/391
- Running existing tests and ensuring that they all pass

Use correct trytes for transaction.value

---

packages/persistence-adapter-level/package-lock.json
packages/persistence-adapter-level/package.json
packages/persistence-adapter-level/src/@types/level/index.d.ts
packages/persistence-adapter-level/src/persistenceAdapterLevel.ts
packages/persistence-adapter-level/test/persistenceAdapterLevel.test.ts

Uses `level` package which bundles `leveldown` (node) and `level-js`(browsers).

fix(persistence-adapter-level): bundled version of level-js & leveldown

---

packages/http-client/README.md
packages/http-client/src/httpClient.ts
packages/http-client/src/request.ts
packages/http-client/src/settings.ts
packages/http-client/test/send.ts
packages/http-client/test/setSettings.test.ts

http-client can be provided  with an agent, this let us behind a proxy use the library.
Fixes #178 

http-client can be supplied with an agent

---

packages/account/src/account.ts

Adds methods to get the current account state;
`getDeposits`:  returns a list of available deposit address and their metadata
`getWithdrawals`: returns a list of withdrawals
`exportState`: returns a full state object
`importState`: imports an account from a state object.

feat(account): state getters & import/export

---

packages/account/src/account.ts
packages/account/src/preset.ts
packages/account/test/account.test.ts
packages/core/src/composeAPI.ts
packages/core/src/index.ts

Aborts `sendToCDA()` if output address was spent from.
Uses [`wereAddressesSpentFrom`](https://docs.iota.org/docs/node-software/0.1/iri/references/api-reference#wereaddressesspentfrom) command.

fix(account): add wereAddressesSpentFrom check

---

packages/account/src/account.ts
packages/account/src/preset.ts
packages/account/test/account.test.ts

- Adds `wereAddressesSpentFrom` check in address generation. In case a seed is opened in more than one device, this check might prevent key/address reuse.
- Refactors account test file

fix(account): add wereAddressesSpentFrom check in address generation

---

packages/account/src/account.ts
packages/account/src/preset.ts
packages/account/test/account.test.ts
packages/core/src/createGetNewAddress.ts
packages/core/test/integration/getNewAddress.test.ts
packages/core/test/integration/nocks/findTransactions.ts
packages/core/test/integration/prepareTransfers.test.ts

- Modifies return type of `isUsedAddress()` to return spent status and list of associated transaction hashes.
- Changes `generateCDA()` to check for transactions on new addresses (besides spent states). If any transactions exist, the address is skipped. In case two (or more) accounts access the same seed, this check might be able to prevent reuse.
- Changes `generateRemainderAddress()` to skip used addresses.
- Emits error events containing the spent state & list of transactions for each used address that is  being skipped.

fix(account): skip used addresses & emit error

---

packages/account/src/account.ts
packages/account/src/preset.ts
packages/account/test/account.test.ts

Attaches generated addresses to tangle until inclusion. Being the other half to #446 this change attempts to notify other wallets using the same seed.

fix(account): attach new address to tangle

---

packages/account/src/preset.ts
packages/account/test/account.test.ts

Lazily checks if inputs with balance have been spent from, before using them in transactions.
Then it drops such inputs and an error event is emitted containing the spent address and its balance.

fix(account): drop spent inputs & emit error

---

packages/account/src/account.ts
packages/account/src/preset.ts
packages/account/test/account.test.ts

Persists trytes of spent addresses but removes their conditions, if any. This change allows to continue monitoring addresses for transactions and emit events with the history of the account.

feat(account): persist spent address

---

packages/bundle/src/index.ts

Adds an argument in `finalizeBundle` to specify which normalized fragments must not contain `13`s. Default value is 3, excluding 13s from all fragments.

feat(bundle): allow to specify number of fragments to be signed

---

packages/converter/src/ascii.ts
packages/converter/test/converter.test.ts

[trytesToAscii()](https://github.com/iotaledger/iota.js/blob/next/packages/converter/src/ascii.ts#L73) converts null trytes to non-breaking whitespaces. This (sometimes) lead to whitespaces at the end of ascii string.
This commit fixes the issue by ignoring null trytes during trytes to ascii conversion.
Fixes https://github.com/iotaledger/iota.js/issues/479
- Added unit tests

Ignore null trytes during trytes to ascii conversion 

---

packages/multisig/src/address.ts
packages/multisig/src/multisig.ts

Default exports (Multisig & Address) are not properly exported from the multisig package. This commit fixes the problem and ensures all relevant objects are exported from the package.
For instance, the exported object after the fix is:
```
{
Address: [Function: Address],
multisigInputValidator: [Function],
sanitizeTransfers: [Function],
createBundle: [Function],
Multisig: [Function: Multisig]
}
```
Manually tested locally.
- [] I have added …

Fix imports for multisig package

---

packages/core/package-lock.json
packages/core/package.json

- Removes unused dependency `babel-cli`
- Bumps `mkdirp` to 0.5.5 (bumps `minimist` to 1.2.5)
- Chore
Unit tests pass

chore(core): Remove unused dep and resolve remaining vulns
